name: my_todos
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+4
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:    
  uses-material-design: true
  assets:
    - assets/icons/repeat/
    - assets/icons/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf

    - family: Montserrat Alternates
      fonts:
        - asset: fonts/Montserrat Alternates/MontserratAlternates-Black.ttf
        - asset: fonts/Montserrat Alternates/MontserratAlternates-Medium.ttf
